name: Build and Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew shadowJar

    - name: Extract version from build.gradle
      id: extract_version
      run: |
        VERSION=$(grep '^version ' build.gradle | awk '{print $3}' | tr -d "'")
        echo "Extracted version is $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Check if Tag Exists
      id: check_tag
      run: |
        if git rev-parse "v${{ steps.extract_version.outputs.version }}" >/dev/null 2>&1; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    - name: Push Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v${{ steps.extract_version.outputs.version }}" -m "Release v${{ steps.extract_version.outputs.version }}"
        git push https://${{ secrets.PUBBUILD }}@github.com/sammyt291/FineHarvest.git "v${{ steps.extract_version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PUBBUILD }}
        
    - name: Create GitHub Release
      if: steps.check_tag.outputs.exists == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.extract_version.outputs.version }}"
        release_name: "Release v${{ steps.extract_version.outputs.version }}"
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.PUBBUILD }}
