name: Build and Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Extract version from gradle.properties
        id: extract_version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          echo "Extracted version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.extract_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag
        uses: negz/create-tag@v1
        if: steps.check_tag.outputs.exists == 'false'
        with:
          token: ${{ secrets.TEST }}
          version: "v${{ steps.extract_version.outputs.version }}"
          message: ""

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TEST }}
          tag_name: "v${{ steps.extract_version.outputs.version }}"
          name: "Release v${{ steps.extract_version.outputs.version }}"
          files: build/libs/*.jar
